##ARABICA
#BRAZIL
library(readxl)
arabica <- read_excel("C:/Users/mantu/OneDrive/Desktop/seminar/arabica.xlsx")
View(arabica)
library(tseries)
attach(arabica)
adf.test(`brazil sp`)
bazsp=log(`brazil sp`)
acf(bazsp)
lbazsp=diff(bazsp)
acf(lbazsp)
adf.test(`brazil fp`)
bazfp=log(`brazil fp`)
acf(bazfp)
lbazfp=diff(bazfp)
acf(lbazfp)
library(vars)
lbazsp<-na.omit(lbazsp)
lbazfp<-na.omit(lbazfp)
VARselect(data.frame(lbazsp,lbazfp))
library(urca)
model1 = ca.jo(data.frame(lbazsp,lbazfp),ecdet = "const",type = "trace",K=2)
summary(model1)
library(lmtest)
grangertest(lbazfp~lbazsp,order = 2,data = arabica)
grangertest(lbazsp~lbazfp,order = 2,data = arabica)
#Honduras
library(tseries)
`honduras sp`<-na.omit(`honduras sp`)
`honduras fp`<-na.omit(`honduras fp`)
adf.test(`honduras sp`)
hondsp = log(`honduras sp`)
acf(hondsp)
lhondsp = diff(hondsp)
acf(lhondsp)
adf.test(`honduras fp`)
hondfp = log(`honduras fp`)
acf(hondfp)
lhondfp = diff(hondfp)
acf(lhondfp)
library(vars)
VARselect(data.frame(lhondsp,lhondfp))
library(urca)
model2 = ca.jo(data.frame(lhondsp,lhondfp),ecdet = "const",type = "trace",K=2)
summary(model2)
library(lmtest)
grangertest(lhondfp~lhondsp,order = 2,data = arabica)
grangertest(lhondsp~lhondfp,order = 2,data = arabica)
##ROBUSTA
#INDIA
library(readxl)
robusta <- read_excel("C:/Users/mantu/OneDrive/Desktop/seminar/robusta.xlsx")
View(robusta)
attach(robusta)
library(tseries)
`India sp`<-na.omit(`India sp`)
`India fp`<-na.omit(`India fp`)
adf.test(`India sp`)
indsp=log(`India sp`)
acf(indsp)
lindsp=diff(indsp)
acf(lindsp)
adf.test(`India fp`)
indfp=log(`India fp`)
acf(indfp)
lindfp=diff(indfp)
acf(lindfp)
library(vars)
VARselect(data.frame(lindsp,lindfp))
library(urca)
model3 = ca.jo(data.frame(lindsp,lindfp),ecdet = "const", type = "trace", K=2)
summary(model3)
library(lmtest)
grangertest(lindfp~lindsp,order = 2,data = robusta)
grangertest(lindsp~lindfp,order = 2,data = robusta)
#UGANDA
library(tseries)
`Uganda sp`<-na.omit(`Uganda sp`)
`Uganda fp`<-na.omit(`Uganda fp`)
adf.test(`Uganda sp`)
ugasp=log(`Uganda sp`)
acf(ugasp)
lugasp=diff(ugasp)
acf(lugasp)
adf.test(`Uganda fp`)
ugafp=log(`Uganda fp`)
acf(ugafp)
lugafp=diff(ugafp)
acf(lugafp)
library(vars)
VARselect(data.frame(lugasp,lugafp))
library(urca)
model4 = ca.jo(data.frame(lugasp,lugafp),ecdet = "const",type = "trace",K=3)
summary(model4)
library(lmtest)
grangertest(lugafp~lugasp,order = 3,data = robusta)
grangertest(lugasp~lugafp,order = 3,data = robusta)
